name: Build on Push to Main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      
      - name: Clean solution
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Testing with the dotnet CLI
        run: dotnet test ./test/Platform.TrustyHands.Professionals.UnitTests/Platform.TrustyHands.Professionals.UnitTests.csproj --configuration Release --no-build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./test/TestResults/TestResults.trx